apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: prod
spec:
  encryptedData:
    image-creds.yaml: AgAABCRSqrAm6FJpg+Z42/ZxvxYTttr/10RUTOoOYrra+7rE64lLVI4z0qOY4j7rv3D+5Zo5TSw6YA0WuOtz8Ss13lERnLyc+LKxoC/s8Npny7rgfObJr2g0mLAGqY5LieU6OeCaZdxKT3pRjg7yP4b7+EsxHMM24G1YhPBrrp+YM0ATVyH67W9kfGXSo8e3ys4tNPsytbB9xWO7VAlyDXKMewb27ZMeEoZNkGJJba5kAIAG/DbPNBBe+6MSu5MFh+VLpf5Ni1FAWcqHyMBgET1mHazjOhLWwjAodo8imm/0+U8sOfFDAWoEx1pVS8z+hsDzHTFj0pH3by8dIzstyQwK+dCGrv0IeUY9FUgdC9IIo+4zKK7clcIEnGp0GOaXGYwpR9vgC4QuvalHpBg9ucJXBauJj+cZLF8KIH9EYiCeffOWSGNB+IQix0CWwzAMFy6AdJ4DVlHNtAiEM6+/q6vRFMG3rRITjh+1dVu7yAUy/yRymxbGwfQRByCCikWiiNpoZTfD6K5UYdGhy2D463/pWAt7j1GObokTJ7oycU2kPZ5hfMZ1J+Ph8MRdiUXH1r8tbwR3695WPeZgIrEH+Xp1kx5hSGJK7wtOwtM3MbdKYcPQdmP4CQFtpStY5EbELMXG6N76gEz4dzyGsOVyH2BpSKSer3GQhbc8AR7tx1BLUcTkkHzRmBhcuHFtZYCTWLDuP/HejyWkE0yhCcDJK7Ju5CZVNkP5arHEEo6XtG+H0Pk6weasONNMvA==

